version: 2
jobs:
  test:
    docker:
      - image: circleci/node:16

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: test
          command: |
            npm run test:ci
            npx codecov@3.0.2
      - run:
          name: lint
          command: npm run lint

      - run:
          name: build
          command: npm run build

workflows:
  version: 2
  build-workflow:
    jobs:
    - test
