name: Validate renovate config

on:
  push:
    paths:
      - 'renovate.json'

jobs:
  build:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Setting up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version-file: .node-version

      - name: validate renovate config
        run: npx --package renovate -c 'renovate-config-validator'
