name: Check codes

on: [push]

jobs:
  build:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Setting up Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: npm install
        run: npm ci --no-audit --no-fund

      - name: lint
        run: npm run lint

      - name: build source
        run: npm run build

      - name: test
        run: |
          npm run test:ci
          npx codecov@3.0.2

      - name: build storybook
        run: npm run build-storybook
