name: Validate renovate config

on:
  push:
    paths:
      - 'renovate.json'

jobs:
  build:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setting up Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version-file: .node-version

      - name: validate renovate config
        run: npx --package renovate -c 'renovate-config-validator'
