name: Validate renovate config

on:
  push:
    paths:
      - 'renovate.json'

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: validate renovate config
        run: npx --package renovate -c 'renovate-config-validator'
