name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x

    steps:
      - uses: actions/checkout@v3

      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: |
          npm run test:ci
          npx codecov@3.0.2

      - name: build storybook
        run: npm run build-storybook

      - name: validate renovate config
        run: npx --package renovate -c 'renovate-config-validator'

      - name: build source
        run: npm run build
