name: Reviewdog

on:
  pull_request:
    paths:
      - '.github/workflows/**'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: reviewdog/action-actionlint@7485c2136bd093d2317a854c72910eebaee35238 # v1
        with:
          tool_name: actionlint
          reporter: github-pr-review
          fail_on_error: true
