name: Reviewdog

on:
  pull_request:
    paths:
      - '.github/workflows/**'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: reviewdog/action-actionlint@7485c2136bd093d2317a854c72910eebaee35238 # v1
        with:
          tool_name: actionlint
          reporter: github-pr-review
          fail_on_error: true
